### ISSUE TITLE
Not caching newly fetched entities.

### ISSUE THREAD

**Issue by Zorotic** [Nigelrex/quick.db-map#1]
https://github.com/Nigelrex/quick.db-map/blob/161c30595bdad7b4766b6acda9dfe9888a851941/main.js#L57

as referenced here you aren’t actually caching anywhere but on set.

**Comment by r-rajaneesh** [comment]
almost forgot, I was thinking about it, I was excited to release the package since it was my very first one!

Thanks for pointing it out!!

Gonna release it ASAP
also when I do

```js
const needCache = this.dbtable.all();
    needCache.forEach(async (value, key) => {
      console.log(value.ID, value.data);
      this.cache.set(value.ID, value.data);
    });
// returns         a "b"
```

**Comment by Zorotic** [comment]
That would not be a smart choice. as you don't want to have useless data sitting in memory that hasn't and wont be accessed. I'd only cache data that is fetched/set, and even then I would have some sort of sweeper that runs over the cache every set amount of time checking for items in the cache that haven't been accessed at all for a while

**Comment by r-rajaneesh** [comment]
that would be for a bit later day,

but to make this a start, if you have perms to merge pr in quick.db repo pls can you merge my pr, does a lot of changes by @Zelak312

**Comment by r-rajaneesh** [comment]
Thanks @Zorotic I fixed it in the latest [quick.db-map@1.0.4](https://npmjs.com/package/quick.db-map)

Thank for pointing out the bug
