### ISSUE TITLE
should be advertised as a wrapper and not a superset

### ISSUE THREAD

**Issue by Zelak312** [Nigelrex/quick.db-map#2]
https://github.com/Nigelrex/quick.db-map/blob/161c30595bdad7b4766b6acda9dfe9888a851941/README.md?plain=1#L3

The definition of wrapper fits more the module you have created. Which is basically a quick.db wrapper with caching

**Comment by r-rajaneesh** [comment]
ok lol sure

**Comment by r-rajaneesh** [comment]
@Zelak312 can you please create a PR so it would be easy for me

**Comment by r-rajaneesh** [comment]
nvm I fixed it myself
